project:
  type: website
  output-dir: docs

website:
  title: "Eli G. Rau"
  navbar:
    left:
      - research/research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: "files/elirau_cv.pdf"
  search: false

format:
  html:
    theme: cosmo
    css: styles.css?v=3
    toc: true
    page-layout: full

editor: visual

resources:
  - CNAME
  - styles.css

