project:
  type: website
  output-dir: docs

website:
  title: "Eli G. Rau"
  navbar:
    left:
      - text: "Research"
        href: research/
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: "files/elirau_cv.pdf"
  search: false

format:
  html:
    theme: cosmo
    css: styles2.css
    toc: true
    page-layout: full

editor: visual

resources:
  - CNAME
  - styles2.css

